// Single-source-of-truth generator for CoatiPay protocol constants.
//
// Source of truth: packages/contracts/src/SettlementHub.sol
// Output:         packages/protocol/src/fee-constants.generated.ts
//
// Usage:
//   pnpm --filter @lacasoft/coatipay-protocol generate:fee-constants          # writes file
//   pnpm --filter @lacasoft/coatipay-protocol check:fee-constants             # exits 1 on drift
//
// Why this exists: protocol invariants (fee bps, batch size cap) are declared
// in Solidity (on-chain, source of truth) AND used in TS (off-chain
// previews, SDK validation, API zod schemas). If they ever drift, off-chain
// code lies to merchants/payers about what the contract will accept.
// Generating from Solidity guarantees they stay in sync.
//
// Filename note: still called `fee-constants` for backward-compat with the
// CI gate name; the scope is now broader ("protocol constants"). Rename
// would touch CI config + every consumer; deferred until next refactor.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SOURCE = resolve(__dirname, '../../contracts/src/SettlementHub.sol')
const TARGET = resolve(__dirname, '../src/fee-constants.generated.ts')

/// Extract any `uintN public constant <NAME> = <expr>;` from the Solidity
/// source. Supports plain integer literals and simple subtraction
/// expressions of two named constants (covers SettlementHub's current
/// pattern, e.g. `OPERATOR_SHARE_BPS = PROTOCOL_FEE_BPS - TREASURY_SHARE_BPS`).
function extractConstant(sol: string, name: string, ctx: Record<string, number>): number {
  // `uint\d+` covers uint8, uint16, uint64, uint96, uint256, etc.
  const re = new RegExp(`uint\\d+\\s+public\\s+constant\\s+${name}\\s*=\\s*([^;]+);`)
  const m = sol.match(re)
  if (!m) throw new Error(`Constant ${name} not found in ${SOURCE}`)
  const expr = m[1].trim()

  // Plain integer literal (with optional `_` digit separators)
  if (/^[\d_]+$/.test(expr)) return Number(expr.replace(/_/g, ''))

  // Subtraction expression: <NAME_A> - <NAME_B>
  const subMatch = expr.match(/^(\w+)\s*-\s*(\w+)$/)
  if (subMatch) {
    const a = ctx[subMatch[1]] ?? extractConstant(sol, subMatch[1], ctx)
    const b = ctx[subMatch[2]] ?? extractConstant(sol, subMatch[2], ctx)
    return a - b
  }

  throw new Error(`Cannot evaluate expression for ${name}: "${expr}". Update generator.`)
}

interface ExtractedConstants {
  PROTOCOL_FEE_BPS: number
  TREASURY_SHARE_BPS: number
  OPERATOR_SHARE_BPS: number
  MAX_BATCH_SIZE: number
}

function generate(): { values: ExtractedConstants; content: string } {
  const sol = readFileSync(SOURCE, 'utf-8')
  const ctx: Record<string, number> = {}
  ctx.PROTOCOL_FEE_BPS = extractConstant(sol, 'PROTOCOL_FEE_BPS', ctx)
  ctx.TREASURY_SHARE_BPS = extractConstant(sol, 'TREASURY_SHARE_BPS', ctx)
  ctx.OPERATOR_SHARE_BPS = extractConstant(sol, 'OPERATOR_SHARE_BPS', ctx)
  ctx.MAX_BATCH_SIZE = extractConstant(sol, 'MAX_BATCH_SIZE', ctx)

  if (ctx.OPERATOR_SHARE_BPS + ctx.TREASURY_SHARE_BPS !== ctx.PROTOCOL_FEE_BPS) {
    throw new Error(
      `Sanity check failed in SettlementHub.sol: OPERATOR_SHARE_BPS (${ctx.OPERATOR_SHARE_BPS}) + TREASURY_SHARE_BPS (${ctx.TREASURY_SHARE_BPS}) !== PROTOCOL_FEE_BPS (${ctx.PROTOCOL_FEE_BPS})`,
    )
  }
  if (ctx.MAX_BATCH_SIZE < 1 || ctx.MAX_BATCH_SIZE > 200) {
    throw new Error(
      `Sanity check failed: MAX_BATCH_SIZE = ${ctx.MAX_BATCH_SIZE} is outside the expected range [1, 200]`,
    )
  }

  const content = `// AUTO-GENERATED — DO NOT EDIT.
//
// Generated by packages/protocol/scripts/generate-fee-constants.ts from
// the Solidity source of truth: packages/contracts/src/SettlementHub.sol.
//
// To regenerate: pnpm --filter @lacasoft/coatipay-protocol generate:fee-constants
// To verify (CI):  pnpm --filter @lacasoft/coatipay-protocol check:fee-constants
//
// Why: protocol invariants are enforced on-chain by SettlementHub.sol.
// Off-chain code (API fee_amount + zod validation, SDK helpers, dashboard)
// must show exactly what the contract will accept. This file mirrors the
// Solidity \`constant\` values so they cannot drift.

export const PROTOCOL_FEE_BPS = ${ctx.PROTOCOL_FEE_BPS}
export const TREASURY_SHARE_BPS = ${ctx.TREASURY_SHARE_BPS}
export const OPERATOR_SHARE_BPS = ${ctx.OPERATOR_SHARE_BPS}
export const MAX_BATCH_SIZE = ${ctx.MAX_BATCH_SIZE}
`

  return {
    values: ctx as ExtractedConstants,
    content,
  }
}

const mode = process.argv.includes('--check') ? 'check' : 'write'

const result = generate()

if (mode === 'check') {
  let existing: string
  try {
    existing = readFileSync(TARGET, 'utf-8')
  } catch {
    console.error(`Drift detected: ${TARGET} does not exist. Run generate:fee-constants.`)
    process.exit(1)
  }
  if (existing !== result.content) {
    console.error(
      `Drift detected: ${TARGET} is out of sync with ${SOURCE}.\nRun \`pnpm --filter @lacasoft/coatipay-protocol generate:fee-constants\` and commit.`,
    )
    process.exit(1)
  }
  console.log(
    `OK — protocol constants in sync (PROTOCOL=${result.values.PROTOCOL_FEE_BPS} TREASURY=${result.values.TREASURY_SHARE_BPS} OPERATOR=${result.values.OPERATOR_SHARE_BPS} MAX_BATCH=${result.values.MAX_BATCH_SIZE})`,
  )
} else {
  writeFileSync(TARGET, result.content)
  console.log(`Wrote ${TARGET}`)
  console.log(`  PROTOCOL_FEE_BPS   = ${result.values.PROTOCOL_FEE_BPS}`)
  console.log(`  TREASURY_SHARE_BPS = ${result.values.TREASURY_SHARE_BPS}`)
  console.log(`  OPERATOR_SHARE_BPS = ${result.values.OPERATOR_SHARE_BPS}`)
  console.log(`  MAX_BATCH_SIZE     = ${result.values.MAX_BATCH_SIZE}`)
}
