// AUTO-GENERATED — DO NOT EDIT.
//
// Generated by packages/protocol/scripts/generate-fee-constants.ts from
// the Solidity source of truth: packages/contracts/src/SettlementHub.sol.
//
// To regenerate: pnpm --filter @lacasoft/coatipay-protocol generate:fee-constants
// To verify (CI):  pnpm --filter @lacasoft/coatipay-protocol check:fee-constants
//
// Why: protocol invariants are enforced on-chain by SettlementHub.sol.
// Off-chain code (API fee_amount + zod validation, SDK helpers, dashboard)
// must show exactly what the contract will accept. This file mirrors the
// Solidity `constant` values so they cannot drift.

export const PROTOCOL_FEE_BPS = 150
export const TREASURY_SHARE_BPS = 45
export const OPERATOR_SHARE_BPS = 105
export const MAX_BATCH_SIZE = 50
